/**
 * Transliteration Utility (GOST 7.79-2000 System B)
 *
 * Converts Cyrillic (Russian) text to URL-safe Latin slugs.
 * Zero external dependencies — uses a hardcoded character map.
 * This exactly matches the backend implementation to ensure UI previews
 * match the actual slugs generated by the server.
 */

// ── GOST 7.79-2000 System B character map ──────────────────
// Multi-char Cyrillic mappings MUST come before single-char
// so we match "Щ" → "shch" before "Ш" → "sh", etc.
const CHAR_MAP: Record<string, string> = {
    // Multi-character mappings (order matters for regex)
    'щ': 'shch', 'Щ': 'Shch',
    'ш': 'sh',   'Ш': 'Sh',
    'ч': 'ch',   'Ч': 'Ch',
    'ж': 'zh',   'Ж': 'Zh',
    'ц': 'ts',   'Ц': 'Ts',
    'ю': 'yu',   'Ю': 'Yu',
    'я': 'ya',   'Я': 'Ya',
    'ё': 'yo',   'Ё': 'Yo',
    'х': 'kh',   'Х': 'Kh',

    // Single-character mappings
    'а': 'a',  'А': 'A',
    'б': 'b',  'Б': 'B',
    'в': 'v',  'В': 'V',
    'г': 'g',  'Г': 'G',
    'д': 'd',  'Д': 'D',
    'е': 'e',  'Е': 'E',
    'з': 'z',  'З': 'Z',
    'и': 'i',  'И': 'I',
    'й': 'j',  'Й': 'J',
    'к': 'k',  'К': 'K',
    'л': 'l',  'Л': 'L',
    'м': 'm',  'М': 'M',
    'н': 'n',  'Н': 'N',
    'о': 'o',  'О': 'O',
    'п': 'p',  'П': 'P',
    'р': 'r',  'Р': 'R',
    'с': 's',  'С': 'S',
    'т': 't',  'Т': 'T',
    'у': 'u',  'У': 'U',
    'ф': 'f',  'Ф': 'F',
    'ы': 'y',  'Ы': 'Y',
    'э': 'e',  'Э': 'E',

    // Silent characters (soft/hard sign) — omit
    'ъ': '', 'Ъ': '',
    'ь': '', 'Ь': '',
};

// Build a regex that matches multi-char sequences first, then single chars.
// Sort keys by length descending so "щ" (→shch) matches before "ш" (→sh).
const TRANSLITERATE_REGEX = new RegExp(
    Object.keys(CHAR_MAP)
        .sort((a, b) => b.length - a.length)
        .map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
        .join('|'),
    'g'
);

/**
 * Convert arbitrary text (primarily Russian) to a URL-safe slug.
 *
 *   transliterateToSlug("Уход за лицом")  → "uhod-za-licom"
 *   transliterateToSlug("Ашваганда Экстракт Корня 500мг") → "ashvaganda-ekstrakt-kornya-500mg"
 *
 * @param text – The source text (Russian or mixed)
 * @returns URL-safe slug
 */
export function transliterateToSlug(text: string): string {
    if (!text || typeof text !== 'string') return '';

    let slug = text;

    // Step 1: Replace Cyrillic characters with Latin equivalents
    slug = slug.replace(TRANSLITERATE_REGEX, match => CHAR_MAP[match] || match);

    // Step 2: Lowercase everything
    slug = slug.toLowerCase();

    // Step 3: Spaces and underscores to hyphens
    slug = slug.replace(/[\s_]+/g, '-');

    // Step 4: Strip anything that isn't a-z, 0-9, or hyphen
    slug = slug.replace(/[^a-z0-9-]/g, '');

    // Step 5: Collapse consecutive hyphens
    slug = slug.replace(/-{2,}/g, '-');

    // Step 6: Trim leading/trailing hyphens
    slug = slug.replace(/^-+|-+$/g, '');

    // Step 7: Enforce max length (80 chars), trimming at last full word boundary
    if (slug.length > 80) {
        slug = slug.substring(0, 80);
        // Don't cut mid-word: trim at last hyphen
        const lastHyphen = slug.lastIndexOf('-');
        if (lastHyphen > 40) {
            slug = slug.substring(0, lastHyphen);
        }
    }

    return slug;
}
